In [1]:
#!pip3 install pandas 
#!pip install --upgrade pip

In [2]:
#!pip install --upgrade --user pip

In [3]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='â„–':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [4]:
df.loc[:,['Gold', 'Gold.1', 'Gold.2']].head()

             Gold  Gold.1  Gold.2
Afghanistan     0       0       0
Algeria         5       0       5
Argentina      18       0      18
Armenia         1       0       1
Australasia     3       0       3

In [5]:
df[df['Gold.2'] == max(df['Gold.2'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [6]:
df[df['Gold.2'] == max(df['Gold.2'])].index[0]

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [7]:
difGG1 = abs(df['Gold'] - df['Gold.1'])

In [8]:
difGG1.head()

Afghanistan     0
Algeria         5
Argentina      18
Armenia         1
Australasia     3
dtype: int64

In [9]:
max(difGG1)

880

In [10]:
df[df['Gold'] - df['Gold.1'] == max(difGG1)]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [11]:
df[df['Gold'] - df['Gold.1'] == max(difGG1)].index[0]

'United States'

In [12]:
difGG1[difGG1 == max(difGG1)].index[0]

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [13]:
difGG1TR = difGG1 / df['Gold.2']

In [14]:
max(difGG1TR.where(difGG1TR < 1).dropna())

0.9615384615384616

In [15]:
difGG1TR[difGG1TR == max(difGG1TR.where(difGG1TR < 1).dropna())].index[0]

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [16]:
points1 = df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']
p1 = pd.Series(points1)
p1.head()

Afghanistan      2
Algeria         27
Argentina      130
Armenia         16
Australasia     22
dtype: int64

In [17]:
len(points1)

146

In [18]:
def puntos():
    p2 = df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']
    Points = pd.Series(p2)
    return Points

In [19]:
puntos().head()

Afghanistan      2
Algeria         27
Argentina      130
Armenia         16
Australasia     22
dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [185]:
census_df = pd.read_csv('census.csv')
census_df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13906,13853,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80473,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50,3,6,1,45,Alabama,Dale County,50251,50251,50358,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43803,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71142,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79465,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38309,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104442,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

### Ejercicios DEA

In [22]:
## Â¿CuÃ¡ntos paÃ­ses tienen Gold?
df[df['Gold']>0]['Gold'].count()

99

In [23]:
## Â¿CuÃ¡ntos paÃ­ses tienen Gold.1?
df[df['Gold.1']>0]['Gold.1'].count()

37

In [24]:
df[df['Gold.1']>0]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN
China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,CHN
Croatia,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,CRO
Czech Republic,5,14,15,15,44,6,7,9,8,24,11,21,24,23,68,CZE
Czechoslovakia,16,49,49,45,143,16,2,8,15,25,32,51,57,60,168,TCH
Estonia,11,9,9,15,33,9,4,2,1,7,20,13,11,16,40,EST
Finland,24,101,84,117,302,22,42,62,57,161,46,143,146,174,463,FIN
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA
Germany,15,174,182,217,573,11,78,78,53,209,26,252,260,270,782,GER
United Team of Germany,3,28,54,36,118,3,8,6,5,19,6,36,60,41,137,EUA
East Germany,5,153,129,127,409,6,39,36,35,110,11,192,165,162,519,GDR
West Germany,5,56,67,81,204,6,11,15,13,39,11,67,82,94,243,FRG
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR
Italy,26,198,166,185,549,22,37,34,43,114,48,235,200,228,663,ITA
Japan,21,130,126,142,398,20,10,17,18,45,41,140,143,160,443,JPN
Kazakhstan,5,16,17,19,52,6,1,3,3,7,11,17,20,22,59,KAZ
South Korea,16,81,82,80,243,17,26,17,10,53,33,107,99,90,296,KOR
Liechtenstein,16,0,0,0,0,18,2,2,5,9,34,2,2,5,9,LIE
Netherlands,25,77,85,104,266,20,37,38,35,110,45,114,123,139,376,NED
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR
Poland,20,64,82,125,271,22,6,7,7,20,42,70,89,132,291,POL
Russia,5,132,121,142,395,6,49,40,35,124,11,181,161,177,519,RUS
Soviet Union,9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204,URS
Unified Team,1,45,38,29,112,1,9,6,8,23,2,54,44,37,135,EUN
Slovakia,5,7,9,8,24,6,2,2,1,5,11,9,11,9,29,SVK
Slovenia,6,4,6,9,19,7,2,4,9,15,13,6,10,18,34,SLO
Spain,22,37,59,35,131,19,1,0,1,2,41,38,59,36,133,ESP
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI
Ukraine,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,UKR
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA
Uzbekistan,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,UZB

In [25]:
## Â¿CuÃ¡ntos paÃ­ses tienen Gold y Gold.1?
## PaÃ­ses que han ganado medalla de oro en Summer y Winter
len(df[(df['Gold']>0) & (df['Gold.1']>0)])

36

In [26]:
df[(df['Gold']>0) & (df['Gold.1']>0)].head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL

In [27]:
##PaÃ­ses que han ganado medalla de oro en Summer y no en Winter
len(df[(df['Gold']>0)&(df['Gold.1']==0)])

63

In [28]:
df[(df['Gold']>0)&(df['Gold.1']==0)].head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ
Azerbaijan,5,6,5,15,26,5,0,0,0,0,10,6,5,15,26,AZE

In [29]:
## PaÃ­ses que han ganado medalla de oro en Winter y no en Summer
df[(df['Gold']==0)&(df['Gold.1']>0)]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Liechtenstein,16,0,0,0,0,18,2,2,5,9,34,2,2,5,9,LIE

In [30]:
len(df[(df['Gold']==0)&(df['Gold.1']>0)])

1

In [31]:
##MÃ¡ximo ganador de oro Winter
df[df['Gold.1'] == max(df['Gold.1'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR

In [32]:
##Â¿QuiÃ©n ha ido mÃ¡s veces a Winter?
df[df['# Winter'] == max(df['# Winter'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN
Finland,24,101,84,117,302,22,42,62,57,161,46,143,146,174,463,FIN
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR
Hungary,25,167,144,165,476,22,0,2,4,6,47,167,146,169,482,HUN
Italy,26,198,166,185,549,22,37,34,43,114,48,235,200,228,663,ITA
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR
Poland,20,64,82,125,271,22,6,7,7,20,42,70,89,132,291,POL
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [33]:
##Â¿QuiÃ©n ha ido mÃ¡s veces a Summer?
df[df['# Summer'] == max(df['# Summer'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR
Greece,27,30,42,39,111,18,0,0,0,0,45,30,42,39,111,GRE
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI

In [34]:
##PaÃ­ses que mÃ¡s han ido a Summer y Winter
df[(df['# Summer'] == max(df['# Summer']))&(df['# Winter'] == max(df['# Winter']))]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI

In [35]:
##MÃ¡ximo ganador de medallas
df[df['Combined total'] == max(df['Combined total'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [36]:
##MÃ¡ximo ganador de medallas en Summer
df[df['Total'] == max(df['Total'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [37]:
##MÃ¡ximo ganador de medallas en Winter
df[df['Total.1'] == max(df['Total.1'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR

In [38]:
##PaÃ­ses con 0 medallas totales
df[df['Combined total'] == 0]

Empty DataFrame
Columns: [# Summer, Gold, Silver, Bronze, Total, # Winter, Gold.1, Silver.1, Bronze.1, Total.1, # Games, Gold.2, Silver.2, Bronze.2, Combined total, ID]
Index: []

In [39]:
##PaÃ­s con menos medallas totales
df[df['Combined total'] == min(df['Combined total'])]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Bahrain,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,BRN
Barbados,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,BAR
Bermuda,17,0,0,1,1,7,0,0,0,0,24,0,0,1,1,BER
Botswana,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1,BOT
Burundi,5,1,0,0,1,0,0,0,0,0,5,1,0,0,1,BDI
Ivory Coast,12,0,1,0,1,0,0,0,0,0,12,0,1,0,1,CIV
Cyprus,9,0,1,0,1,10,0,0,0,0,19,0,1,0,1,CYP
Djibouti,7,0,0,1,1,0,0,0,0,0,7,0,0,1,1,DJI
Eritrea,4,0,0,1,1,0,0,0,0,0,4,0,0,1,1,ERI
Gabon,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1,GAB
Grenada,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1,GRN
Guatemala,13,0,1,0,1,1,0,0,0,0,14,0,1,0,1,GUA
Guyana,16,0,0,1,1,0,0,0,0,0,16,0,0,1,1,GUY
Iraq,13,0,0,1,1,0,0,0,0,0,13,0,0,1,1,IRQ
Macedonia,5,0,0,1,1,5,0,0,0,0,10,0,0,1,1,MKD
Mauritius,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,MRI
Montenegro,2,0,1,0,1,2,0,0,0,0,4,0,1,0,1,MNE
Netherlands Antilles,13,0,1,0,1,2,0,0,0,0,15,0,1,0,1,AHO
Niger,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,NIG
Paraguay,11,0,1,0,1,1,0,0,0,0,12,0,1,0,1,PAR
Senegal,13,0,1,0,1,5,0,0,0,0,18,0,1,0,1,SEN
Sudan,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,SUD
Togo,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1,TOG
Tonga,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1,TGA
United Arab Emirates,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1,UAE
Virgin Islands,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1,ISV

In [40]:
##Promedio de medallas totales ganadas
df['Combined total'].mean()

120.4041095890411

In [41]:
df.sort_values(by=['Combined total'], ascending=False).head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA
Soviet Union,9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204,URS
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR
Germany,15,174,182,217,573,11,78,78,53,209,26,252,260,270,782,GER
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA

In [42]:
df.loc['Russia'] + df.loc['Soviet Union']

# Summer              14
Gold                 527
Silver               440
Bronze               438
Total               1405
# Winter              15
Gold.1               127
Silver.1              97
Bronze.1              94
Total.1              318
# Games               29
Gold.2               654
Silver.2             537
Bronze.2             532
Combined total      1723
ID                RUSURS
dtype: object

In [43]:
df.loc['Russia']

# Summer            5
Gold              132
Silver            121
Bronze            142
Total             395
# Winter            6
Gold.1             49
Silver.1           40
Bronze.1           35
Total.1           124
# Games            11
Gold.2            181
Silver.2          161
Bronze.2          177
Combined total    519
ID                RUS
Name: Russia, dtype: object

In [44]:
df.loc['Soviet Union']

# Summer             9
Gold               395
Silver             319
Bronze             296
Total             1010
# Winter             9
Gold.1              78
Silver.1            57
Bronze.1            59
Total.1            194
# Games             18
Gold.2             473
Silver.2           376
Bronze.2           355
Combined total    1204
ID                 URS
Name: Soviet Union, dtype: object

In [184]:
census_df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,40,3,6,1,0,Alabama,4779736,4780127,4785161,4801108,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
Alabama,50,3,6,1,1,Autauga County,54571,54571,54660,55253,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
Alabama,50,3,6,1,3,Baldwin County,182265,182265,183193,186659,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
Alabama,50,3,6,1,5,Barbour County,27457,27457,27341,27226,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
Alabama,50,3,6,1,7,Bibb County,22915,22919,22861,22733,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
Alabama,50,3,6,1,9,Blount County,57322,57322,57373,57711,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
Alabama,50,3,6,1,11,Bullock County,10914,10915,10887,10629,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
Alabama,50,3,6,1,13,Butler County,20947,20946,20944,20673,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
Alabama,50,3,6,1,15,Calhoun County,118572,118586,118437,117768,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
Alabama,50,3,6,1,17,Chambers County,34215,34170,34098,33993,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
Alabama,50,3,6,1,19,Cherokee County,25989,25986,25976,26080,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
Alabama,50,3,6,1,21,Chilton County,43643,43631,43665,43739,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
Alabama,50,3,6,1,23,Choctaw County,13859,13858,13841,13593,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
Alabama,50,3,6,1,25,Clarke County,25833,25840,25767,25570,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
Alabama,50,3,6,1,27,Clay County,13932,13932,13880,13670,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
Alabama,50,3,6,1,29,Cleburne County,14972,14972,14973,14971,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
Alabama,50,3,6,1,31,Coffee County,49948,49948,50177,50448,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
Alabama,50,3,6,1,33,Colbert County,54428,54428,54514,54443,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
Alabama,50,3,6,1,35,Conecuh County,13228,13228,13208,13121,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
Alabama,50,3,6,1,37,Coosa County,11539,11758,11758,11348,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
Alabama,50,3,6,1,39,Covington County,37765,37765,37796,38060,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
Alabama,50,3,6,1,41,Crenshaw County,13906,13906,13853,13896,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
Alabama,50,3,6,1,43,Cullman County,80406,80410,80473,80469,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
Alabama,50,3,6,1,45,Dale County,50251,50251,50358,50109,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
Alabama,50,3,6,1,47,Dallas County,43820,43820,43803,43178,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
Alabama,50,3,6,1,49,DeKalb County,71109,71115,71142,71387,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
Alabama,50,3,6,1,51,Elmore County,79303,79296,79465,80012,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
Alabama,50,3,6,1,53,Escambia County,38319,38319,38309,38213,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
Alabama,50,3,6,1,55,Etowah County,104430,104427,104442,104236,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
Alabama,50,3,6,1,57,Fayette County,17241,17241,17231,17062,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wisconsin,50,2,3,55,131,Washington County,131887,131885,131967,132225,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
Wisconsin,50,2,3,55,133,Waukesha County,389891,389938,390076,390808,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
Wisconsin,50,2,3,55,135,Waupaca County,52410,52410,52422,52342,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
Wisconsin,50,2,3,55,137,Waushara County,24496,24496,24506,24581,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
Wisconsin,50,2,3,55,139,Winnebago County,166994,166994,167059,167630,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
Wisconsin,50,2,3,55,141,Wood County,74749,74749,74807,74647,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
Wyoming,40,4,8,56,0,Wyoming,563626,563767,564516,567768,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573
Wyoming,50,4,8,56,1,Albany County,36299,36299,36428,36908,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
Wyoming,50,4,8,56,3,Big Horn County,11668,11668,11672,11745,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
Wyoming,50,4,8,56,5,Campbell County,46133,46133,46244,46600,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
Wyoming,50,4,8,56,7,Carbon County,15885,15885,15837,15817,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
Wyoming,50,4,8,56,9,Converse County,13833,13833,13826,13728,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
Wyoming,50,4,8,56,11,Crook County,7083,7083,7114,7129,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
Wyoming,50,4,8,56,13,Fremont County,40123,40123,40222,40591,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
Wyoming,50,4,8,56,15,Goshen County,13249,13247,13408,13597,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
Wyoming,50,4,8,56,17,Hot Springs County,4812,4812,4813,4818,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
Wyoming,50,4,8,56,19,Johnson County,8569,8569,8581,8636,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
Wyoming,50,4,8,56,21,Laramie County,91738,91881,92271,92663,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
Wyoming,50,4,8,56,23,Lincoln County,18106,18106,18091,18022,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
Wyoming,50,4,8,56,25,Natrona County,75450,75450,75472,76420,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
Wyoming,50,4,8,56,27,Niobrara County,2484,2484,2492,2485,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
Wyoming,50,4,8,56,29,Park County,28205,28205,28259,28473,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
Wyoming,50,4,8,56,31,Platte County,8667,8667,8678,8701,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
Wyoming,50,4,8,56,33,Sheridan County,29116,29116,29146,29275,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
Wyoming,50,4,8,56,35,Sublette County,10247,10247,10244,10142,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
Wyoming,50,4,8,56,37,Sweetwater County,43806,43806,43593,44041,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
Wyoming,50,4,8,56,39,Teton County,21294,21294,21297,21482,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
Wyoming,50,4,8,56,41,Uinta County,21118,21118,21102,20912,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
Wyoming,50,4,8,56,43,Washakie County,8533,8533,8545,8469,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
Wyoming,50,4,8,56,45,Weston County,7208,7208,7181,7114,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [58]:
len(census_df['STNAME'].unique())

51

In [96]:
census_df[census_df['STNAME'] == 'Virginia']

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Virginia,40,3,5,51,0,Virginia,Virginia,8001024,8001045,8025787,...,1.360760,0.614199,0.346268,-2.197521,-2.849964,5.004781,4.923775,4.447050,2.315622,1.793779
Virginia,50,3,5,51,1,Virginia,Accomack County,33164,33164,33165,...,1.625233,-2.312278,-9.650326,-0.090905,-1.606767,3.280563,-0.030030,-7.659947,2.212021,0.848858
Virginia,50,3,5,51,3,Virginia,Albemarle County,98970,98998,99236,...,5.393263,6.682955,2.841173,6.466120,6.426919,8.415091,9.960268,6.268154,10.384396,10.330677
Virginia,50,3,5,51,5,Virginia,Alleghany County,16250,16261,16211,...,6.267089,-3.008627,2.898729,-10.910565,-5.386395,6.451415,-2.947226,3.022080,-10.785872,-5.259656
Virginia,50,3,5,51,7,Virginia,Amelia County,12690,12695,12742,...,-2.117730,-1.098168,-1.729696,4.473571,9.576456,-0.392172,-0.549084,-1.179338,5.101440,10.199315
Virginia,50,3,5,51,9,Virginia,Amherst County,32353,32354,32385,...,-7.658440,10.655433,-6.280260,-3.423592,-3.094911,-7.596428,10.841284,-6.063700,-3.205727,-2.844817
Virginia,50,3,5,51,11,Virginia,Appomattox County,14973,14975,15035,...,-0.998735,6.171201,2.635133,2.623983,7.561930,-0.998735,6.171201,2.635133,2.623983,7.561930
Virginia,50,3,5,51,13,Virginia,Arlington County,207627,207676,209429,...,13.160459,3.500022,-1.779204,-17.263795,-8.464462,22.846518,13.447932,8.216526,-6.129001,2.720563
Virginia,50,3,5,51,15,Virginia,Augusta County,73750,73736,73478,...,2.294279,-1.584743,3.528338,1.551004,3.259852,2.579366,-1.246123,3.906857,1.996075,3.704377
Virginia,50,3,5,51,17,Virginia,Bath County,4731,4727,4712,...,-4.694836,3.656307,-7.145951,-7.434944,-13.305244,-4.054631,4.301538,-6.496319,-6.778920,-12.639982
Virginia,50,3,5,51,19,Virginia,Bedford County,68676,74871,74997,...,5.460270,2.220621,5.120105,11.390844,8.164373,5.938542,2.643597,5.607108,11.899714,8.681105
Virginia,50,3,5,51,21,Virginia,Bland County,6824,6824,6810,...,0.736648,-3.268217,2.989537,-6.020470,0.151895,0.589319,-3.416772,2.840060,-6.170981,0.000000
Virginia,50,3,5,51,23,Virginia,Botetourt County,33148,33148,33182,...,-3.411424,5.734810,-2.747211,4.564140,9.870302,-3.411424,5.795177,-2.626455,4.685044,10.020764
Virginia,50,3,5,51,25,Virginia,Brunswick County,17434,17432,17413,...,-12.903599,-4.503451,-2.528296,-4.739758,-1.851575,-12.845735,-4.386478,-2.410701,-4.621264,-1.732119
Virginia,50,3,5,51,27,Virginia,Buchanan County,24098,24095,24040,...,-5.336780,1.505300,-7.024333,-17.085255,-12.229887,-4.878150,2.216136,-6.267219,-16.230993,-11.359432
Virginia,50,3,5,51,29,Virginia,Buckingham County,17146,17140,17111,...,3.207745,-8.588455,1.988304,-13.792699,5.594982,3.790972,-8.004207,2.631579,-13.147083,6.242822
Virginia,50,3,5,51,31,Virginia,Campbell County,54842,54851,54934,...,-2.876493,-2.859485,2.564802,0.744352,-0.471925,-2.694436,-2.640925,2.855844,1.052985,-0.163359
Virginia,50,3,5,51,33,Virginia,Caroline County,28545,28558,28643,...,-3.592104,3.259079,5.664166,10.156409,-0.368022,-3.278231,3.536448,5.938793,10.461101,-0.066913
Virginia,50,3,5,51,35,Virginia,Carroll County,30042,30087,30086,...,3.024160,-2.298697,2.641345,-2.419314,6.535838,3.290020,-2.265383,2.708215,-2.318509,6.636907
Virginia,50,3,5,51,36,Virginia,Charles City County,7256,7256,7271,...,-0.137751,-9.017758,-3.221740,-9.480685,8.532423,-0.137751,-9.017758,-3.221740,-9.480685,8.532423
Virginia,50,3,5,51,37,Virginia,Charlotte County,12586,12575,12547,...,-3.833713,-6.909573,-9.156099,-9.726195,1.968262,-2.236332,-5.945447,-8.102743,-8.581937,3.116414
Virginia,50,3,5,51,41,Virginia,Chesterfield County,316236,316231,317312,...,2.696529,4.079759,4.708185,6.764081,1.292871,4.615455,6.133599,6.649736,8.919867,3.558389
Virginia,50,3,5,51,43,Virginia,Clarke County,14034,14029,14038,...,12.605340,7.022225,1.750578,4.956370,-3.202451,12.746973,7.584003,2.380786,5.584642,-2.506266
Virginia,50,3,5,51,45,Virginia,Craig County,5190,5173,5176,...,6.729475,-3.453569,2.311471,8.441247,-3.253277,6.729475,-3.453569,2.311471,8.441247,-3.253277
Virginia,50,3,5,51,47,Virginia,Culpeper County,46689,46691,46848,...,4.863132,2.986142,8.125266,7.234793,-0.263828,5.563932,3.553929,8.748688,8.013609,0.507362
Virginia,50,3,5,51,49,Virginia,Cumberland County,10052,10055,10044,...,-4.982809,-19.810941,-0.811729,-2.539747,-12.987013,-4.982809,-19.911504,-0.913196,-2.641337,-13.089273
Virginia,50,3,5,51,51,Virginia,Dickenson County,15903,15892,15870,...,-6.701862,-4.135781,-11.372033,-7.411019,-10.058841,-6.448962,-3.944899,-11.179286,-7.215992,-9.861609
Virginia,50,3,5,51,53,Virginia,Dinwiddie County,28001,28001,28019,...,1.530331,-0.496014,-5.668332,-3.022222,-6.545064,2.242113,-0.106289,-5.207780,-2.311111,-5.829757
Virginia,50,3,5,51,57,Virginia,Essex County,11151,11146,11147,...,1.521729,-1.789149,1.700604,-11.765763,1.800666,1.790270,-1.252404,2.237637,-11.226873,2.340866
Virginia,50,3,5,51,59,Virginia,Fairfax County,1081726,1081685,1086835,...,-1.068978,-4.301956,-5.331461,-15.828378,-14.700525,7.703572,4.663819,3.910625,-5.532061,-4.358958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginia,50,3,5,51,595,Virginia,Emporia city,5927,5927,5934,...,-20.091946,0.861549,-16.231783,-12.793177,-12.626263,-19.581134,1.378479,-15.708177,-12.260128,-11.904762
Virginia,50,3,5,51,600,Virginia,Fairfax city,22565,22542,22595,...,-9.494160,3.886039,4.591782,-12.078830,-11.780242,-1.987150,11.614453,12.101706,-3.560076,-3.353806
Virginia,50,3,5,51,610,Virginia,Falls Church city,12332,12289,12440,...,8.985726,17.050298,8.845543,-8.867362,14.759069,16.142499,23.482911,15.876616,-1.415797,22.065539
Virginia,50,3,5,51,620,Virginia,Franklin city,8582,8580,8593,...,-20.824754,1.306258,13.319974,-22.059691,-2.601549,-20.001177,2.375015,14.498733,-20.644096,-1.182522
Virginia,50,3,5,51,630,Virginia,Fredericksburg city,24286,24023,24202,...,41.450153,38.871402,13.366598,1.710590,-20.133633,46.827037,43.991050,18.064939,7.127457,-14.745760
Virginia,50,3,5,51,640,Virginia,Galax city,7042,6989,7009,...,-34.028381,7.037607,10.325771,-3.905685,-2.603790,-34.028381,6.890990,10.471204,-3.616375,-2.314480
Virginia,50,3,5,51,650,Virginia,Hampton city,137436,137510,137448,...,-12.165708,-4.777838,-5.886231,-3.299550,-16.713640,-11.071013,-1.424585,-3.562335,-0.995679,-14.066585
Virginia,50,3,5,51,660,Virginia,Harrisonburg city,48914,48907,49048,...,-0.506047,15.368294,-9.493300,3.476716,-9.427841,6.700066,21.634592,-2.793296,11.106175,-1.946639
Virginia,50,3,5,51,670,Virginia,Hopewell city,22591,22591,22634,...,-10.109744,-13.095850,-12.295359,-5.782958,3.594294,-8.779514,-11.844369,-10.944221,-4.337219,4.987083
Virginia,50,3,5,51,678,Virginia,Lexington city,7042,7038,7060,...,-26.080103,7.364621,21.211474,2.386802,6.106446,-24.503833,10.108303,24.058652,5.896806,9.437235
Virginia,50,3,5,51,680,Virginia,Lynchburg city,75568,75608,75703,...,5.606986,5.023234,3.415884,-4.346912,4.115148,9.073600,8.475896,7.062918,0.000000,8.407021
Virginia,50,3,5,51,683,Virginia,Manassas city,37821,37839,38267,...,4.959831,11.523317,1.129763,-15.934999,-12.029786,12.167084,17.612057,7.760981,-8.440456,-4.571319
Virginia,50,3,5,51,685,Virginia,Manassas Park city,14273,14241,14439,...,23.974337,0.261003,7.703081,-20.727021,-10.529320,29.849738,5.676813,13.241660,-14.175014,-3.869208
Virginia,50,3,5,51,690,Virginia,Martinsville city,13821,13821,13729,...,-4.154670,-0.585223,0.881931,-3.464161,5.294702,-3.571559,-0.219459,1.249403,-2.948222,5.809464
Virginia,50,3,5,51,700,Virginia,Newport News city,180719,180911,180891,...,-15.201079,-14.035321,-3.871746,-5.851729,-13.286414,-12.170835,-8.816492,0.182525,-1.582439,-8.501332
Virginia,50,3,5,51,710,Virginia,Norfolk city,242803,242831,242893,...,-7.120671,-6.059269,-15.121495,-7.619544,-12.521519,-4.538811,1.548525,-10.026696,-2.539848,-6.309481
Virginia,50,3,5,51,720,Virginia,Norton city,3958,3951,3969,...,3.006012,5.210272,-12.406948,-3.732736,-29.138407,6.012024,7.195137,-10.173697,-1.244245,-26.626476
Virginia,50,3,5,51,730,Virginia,Petersburg city,32420,32420,32507,...,-26.319873,-11.666196,3.470919,-4.878655,-6.025772,-24.116205,-7.150249,6.910569,-1.087598,-1.761379
Virginia,50,3,5,51,735,Virginia,Poquoson city,12150,12157,12147,...,-8.100847,6.122280,-0.907516,-6.128364,1.743245,-7.522215,7.528750,-0.330006,-5.465839,2.407338
Virginia,50,3,5,51,740,Virginia,Portsmouth city,95535,95535,95484,...,-2.770619,-0.790197,-10.523585,-8.973698,-4.225733,-2.132854,2.214632,-8.883815,-7.505843,-2.466746
Virginia,50,3,5,51,750,Virginia,Radford city,16408,16408,16450,...,10.836845,-12.090017,20.046855,10.213260,-6.150662,14.870560,-8.678477,23.783399,14.275352,-2.126865
Virginia,50,3,5,51,760,Virginia,Richmond city,204214,204175,204151,...,4.002210,11.553301,6.750586,5.394101,8.696269,7.308173,14.609274,9.951701,8.963864,12.250714
Virginia,50,3,5,51,770,Virginia,Roanoke city,97032,96919,96778,...,-5.783571,4.164936,1.105847,-0.844981,-8.163429,-0.629996,8.770985,6.208975,4.828464,-2.524152
Virginia,50,3,5,51,775,Virginia,Salem city,24802,24848,24916,...,-7.716577,6.017330,7.410949,4.709421,-0.787681,-4.059241,9.186457,10.837517,8.666917,3.229491
Virginia,50,3,5,51,790,Virginia,Staunton city,23746,23746,23833,...,7.352788,-4.383493,18.344044,6.414342,-3.030117,8.731435,-3.089319,19.883114,8.059045,-1.433163
Virginia,50,3,5,51,800,Virginia,Suffolk city,84585,84596,84876,...,-6.353547,-1.352695,1.333146,6.831471,7.389852,-5.775952,0.658703,2.677987,8.035663,8.840410
Virginia,50,3,5,51,810,Virginia,Virginia Beach city,437994,437966,439038,...,-1.147374,-7.624586,-3.757063,-7.275564,-7.954636,1.693851,-1.838632,0.514054,-2.853337,-2.954769
Virginia,50,3,5,51,820,Virginia,Waynesboro city,21006,21020,21038,...,-6.039279,-4.237187,1.521889,0.757396,6.701502,-5.563745,-3.665881,2.187716,1.467456,7.404457
Virginia,50,3,5,51,830,Virginia,Williamsburg city,14068,13673,13694,...,27.629043,19.359284,2.841582,-8.084074,5.620797,35.625045,26.799862,11.095700,1.279978,14.988792
Virginia,50,3,5,51,840,Virginia,Winchester city,26203,26201,26162,...,10.971135,7.919393,3.965631,-5.697277,-10.609691,14.413801,10.819453,6.976573,-2.227782,-7.097518

In [111]:
##Contar cuÃ¡ntos County tiene un estado en particular
census_df[census_df['STNAME'] == max(census_df.loc[:]['COUNTY'])]

Empty DataFrame
Columns: [SUMLEV, REGION, DIVISION, STATE, COUNTY, STNAME, CTYNAME, CENSUS2010POP, ESTIMATESBASE2010, POPESTIMATE2010, POPESTIMATE2011, POPESTIMATE2012, POPESTIMATE2013, POPESTIMATE2014, POPESTIMATE2015, NPOPCHG_2010, NPOPCHG_2011, NPOPCHG_2012, NPOPCHG_2013, NPOPCHG_2014, NPOPCHG_2015, BIRTHS2010, BIRTHS2011, BIRTHS2012, BIRTHS2013, BIRTHS2014, BIRTHS2015, DEATHS2010, DEATHS2011, DEATHS2012, DEATHS2013, DEATHS2014, DEATHS2015, NATURALINC2010, NATURALINC2011, NATURALINC2012, NATURALINC2013, NATURALINC2014, NATURALINC2015, INTERNATIONALMIG2010, INTERNATIONALMIG2011, INTERNATIONALMIG2012, INTERNATIONALMIG2013, INTERNATIONALMIG2014, INTERNATIONALMIG2015, DOMESTICMIG2010, DOMESTICMIG2011, DOMESTICMIG2012, DOMESTICMIG2013, DOMESTICMIG2014, DOMESTICMIG2015, NETMIG2010, NETMIG2011, NETMIG2012, NETMIG2013, NETMIG2014, NETMIG2015, RESIDUAL2010, RESIDUAL2011, RESIDUAL2012, RESIDUAL2013, RESIDUAL2014, RESIDUAL2015, GQESTIMATESBASE2010, GQESTIMATES2010, GQESTIMATES2011, GQESTIMATES2012, GQESTIMATES2013, GQESTIMATES2014, GQESTIMATES2015, RBIRTH2011, RBIRTH2012, RBIRTH2013, RBIRTH2014, RBIRTH2015, RDEATH2011, RDEATH2012, RDEATH2013, RDEATH2014, RDEATH2015, RNATURALINC2011, RNATURALINC2012, RNATURALINC2013, RNATURALINC2014, RNATURALINC2015, RINTERNATIONALMIG2011, RINTERNATIONALMIG2012, RINTERNATIONALMIG2013, RINTERNATIONALMIG2014, RINTERNATIONALMIG2015, RDOMESTICMIG2011, RDOMESTICMIG2012, RDOMESTICMIG2013, RDOMESTICMIG2014, RDOMESTICMIG2015, RNETMIG2011, RNETMIG2012, RNETMIG2013, RNETMIG2014, RNETMIG2015]
Index: []

[0 rows x 100 columns]

In [107]:
census_df.loc['Virginia', ['COUNTY', 'CTYNAME']].count()

COUNTY     134
CTYNAME    134
dtype: int64

In [121]:
len(census_df.loc['Virginia']['COUNTY'])

134

In [131]:
##STNAME con mÃ¡s COUNTY

In [166]:
census_df = census_df.set_index(['STNAME'])

In [134]:
len(census_df.loc['Virginia'])

134

In [175]:
county_count = pd.DataFrame()

In [174]:
census_df.loc['Virginia']['CTYNAME'].count()

134

In [188]:
state_df = pd.DataFrame(census_df['STNAME'].unique())

In [194]:
state_df[0]

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: 0, dtype: object

In [195]:
for state in state_df:
    ctycount = census_df[state].count()
    state_df['COUNTIES'] = ctycount

KeyError: 0